# SaveXTube 完整配置文件
# 创建文件时，若需要保留中文注释，请务必确保本文件编码为 UTF-8，否则会无法读取。

[telegram]
# Telegram Bot 配置
telegram_bot_token = "xxx" # 核心配置，必选项，操作telegram机器人必须配置的参数
telegram_bot_api_id = "xxx" # 只有需要使用 telegram 保存视频才需要配置
telegram_bot_api_hash = "xxx" # 只有需要使用 telegram 保存视频才需要配置
telegram_bot_allowed_user_ids = "xxx" # 允许操作telegram机器人的telegram用户，不填写任何人只要知道你telegram机器人名称，都可以给你机器人发链接下载

[proxy]
# 代理服务器配置
#proxy_host = "http://192.168.2.1:7890"

[netease]
# 网易云音乐配置
ncm_quality_level = "无损"
ncm_download_lyrics = true
ncm_dir_format = "{ArtistName}/{AlbumName}"
ncm_album_folder_format = "{AlbumName}({ReleaseDate})"
ncm_song_file_format = "{SongName}"

[apple_music]
# Apple Music 配置
amdp = true
amd_wrapper_decrypt = "192.168.2.134:10020"
amd_wrapper_get = "192.168.2.134:20020"
amd_region = "cn"

[bilibili]
# Bilibili 配置
bilibili_poll_interval = 1

[qbittorrent]
# qBittorrent 连接配置
qb_host = "192.168.2.134"
qb_port = 8988
qb_username = "admin"
qb_password = "xxx"

[logging]
# 日志配置
log_level = "INFO"
log_dir = "/app/logs"
log_max_size = 10
log_backup_count = 5
log_to_console = true
log_to_file = true

[youtube]
# YouTube 配置
youtube_convert_to_mp4 = true
